name: Celeritas CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        name: Build and Unit Tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/first-interaction@v1
                with:
                    repo-token: ${{ secrets.GITHUB_TOKEN }}
                    issue-message: 'Thank you for creating your first issue. It is really nice that you are interested in Celeritas'
                    pr-message: 'Thank you for creating your first pull request. It is really nice that you are interested in Celeritas.'
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup JDK 17
                uses: actions/setup-java@v1
                with:
                    java-version: 17
            -   name: Cache
                uses: actions/cache@v1
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2
            -   name: Test
                run: mvn clean install -B
